name: BD Actions Blackduck Simplification Test
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:  
jobs:
  build:
    runs-on: [ mac-sh-p ]
    #runs-on: [ madhu_windows_runner ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Black Duck Full Scan
        uses: blackduck-inc/black-duck-security-scan@v2
        #uses: blackduck-inc/black-duck-security-scan@main
        ### Use below configuration to set specific detect environment variables
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          #DETECT_EXCLUDED_DIRECTORIES: /Users/madhusud/PI_3_2023/Local_Anlaysis_Testing_INTDELIVER-169/Github_Runners/actions-runner/_work/Node_Goat_E2E/Node_Goat_E2E/config, /Users/madhusud/PI_3_2023/Local_Anlaysis_Testing_INTDELIVER-169/Github_Runners/actions-runner/_work/Node_Goat_E2E/Node_Goat_E2E/app
          #DETECT_BLACKDUCK_RAPID_COMPARE_MODE: BOM_COMPARE
        with:
          ### SCANNING: Required fields
          blackducksca_url: ${{ secrets.BLACKDUCK_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          #blackduck_scan_full: false
          #synopsys_bridge_download_url: https://artifactory.internal.synopsys.com/artifactory/clops-local/clops.sig.synopsys.com/synopsys-bridge/2.8.54/synopsys-bridge-2.8.54-macos_arm.zip
          #synopsys_bridge_download_version: 2.3.0
          ### SCANNING: Optional fields
          #blackducksca_scan_failure_severities: 'BLOCKER,CRITICAL'

          bridgecli_download_url: "https://artifactory.tools.duckutil.net/artifactory/clops-local/integrations/bridge/binaries/bridge-cli-bundle/3.9.2rc1/bridge-cli-bundle-3.9.2rc1-macos_arm.zip"
          #bridgecli_download_url: "https://artifactory.tools.duckutil.net/artifactory/clops-local/integrations/bridge/binaries/bridge-cli-bundle/3.7.1rc1/bridge-cli-bundle-3.7.1rc1-win64.zip"
          
          ### FIX PULL REQUEST CREATION: Uncomment below to enable
          blackducksca_fixpr_enabled: true
          blackducksca_fixpr_maxCount : 2
          blackducksca_fixpr_filter_severities: 'Critical, High'
          #blackduck_fixpr_filter_severities: 'Critical'
          blackducksca_fixpr_useUpgradeGuidance: 'SHORT_TERM,LONG_TERM'
          #blackduck_fixpr_useUpgradeGuidance: 'SHORT_TERM'
          github_token: ${{ secrets.GIT_PAT_TOKEN }} # Required when Fix PRs is enabled
          
          ### PULL REQUEST COMMENTS: Uncomment below to enable
          blackducksca_prComment_enabled: true 
          
          ### SARIF report generation and upload to GitHub Adavanced Security: Uncomment below to enable
          blackducksca_reports_sarif_create: true # Create Black Duck SARIF report and upload it as artifact
          #blackducksca_reports_sarif_file_path: "/Users/madhusud/Sarif_Reports/BD_Security_Scan_Sarif_Report.json"
          blackduck_upload_sarif_report: true  # Upload Black Duck SARIF report in GitHub Advanced Security tab
          blackducksca_reports_sarif_severities: 'CRITICAL,HIGH'
          blackducksca_reports_sarif_groupSCAIssues: false
          #include_diagnostics: false
          #github_token: ${{ secrets.GITHUB_TOKEN }}

          #### Blackduck Arbitrary product-related CL arguments
          # detect_search_depth: 3
          # detect_args: '--detect.diagnostic=true'
          
          #detect_config_path: '/Users/madhusud/Github_Repos/Config_Files/application.properties'
          #detect_config_path: 'C:\\Users\\madhusud\\e2e_testing\\repos\\Config_Path\\blackduck.properties'

          ### Async Mode Test
          #blackducksca_waitForScan: false

          ### BD Install Directory
          #detect_install_directory: "/Users/madhusud/Github_Repos/Blackduck_Install_Directory"
          
          ###Badges
          #blackduck_policy_badges_create: true
          #blackduck_policy_badges_maxCount: 5
          #include_diagnostics: true

          #mark_build_status: 'success'

          ## Self Signed Certificate Test
          #network_ssl_cert_file: "/Users/madhusud/Bridge_Testing/Self_Signed_Certificate_Test/8443/covserver 1.crt"
          #network_ssl_cert_file: "/Users/madhusud/Bridge_Testing/Self_Signed_Certificate_Test/8443/cov-local-cert.pem"
          #network_ssl_trustAll: 'true'
